dist: focal
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "nightly"
git:
  depth: 3
  submodules: true
branches:
  only:
    - master
install:
  - sudo pip install -r requirements.txt
script:
  - sudo python3 setup.py install